# Generated by Django 4.0.3 on 2022-04-04 21:04

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=150, null=True, verbose_name='bio')),
                ('photo_profile', models.ImageField(default='default-profile-img.png', upload_to=account.models.get_image_path, verbose_name='foto profile')),
                ('nim', models.IntegerField(default=211, verbose_name='nomor induk mahasiswa')),
                ('gender', models.CharField(choices=[('FEMALE', 'Perempuan'), ('MALE', 'Laki-laki')], max_length=6, verbose_name='jenis kelamin')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
