# Generated by Django 4.0.3 on 2022-04-07 18:22

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Masukkan nama kelas yang akan di sediakan.', max_length=30, verbose_name='title')),
                ('slug', models.SlugField()),
                ('desc', models.TextField(max_length=255, verbose_name='deskripsi')),
                ('is_active', models.BooleanField(default=False, verbose_name='aktif')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='dibuat')),
                ('logo', models.ImageField(upload_to='logo', verbose_name='logo')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='konten')),
                ('opened', models.TimeField(verbose_name='jam buka')),
                ('closed', models.TimeField(verbose_name='jam tutup')),
                ('member', models.ManyToManyField(blank=True, related_name='user_member_in_rooms', to=settings.AUTH_USER_MODEL)),
                ('mentor', models.ManyToManyField(related_name='user_mentor_in_rooms', to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
