# Generated by Django 4.0.3 on 2022-04-09 17:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authenticatedjoinquitroom',
            name='choices',
            field=models.CharField(choices=[('join', 'Gabung'), ('quit', 'Keluar')], default=django.utils.timezone.now, max_length=4, verbose_name='pilihan'),
            preserve_default=False,
        ),
    ]
