# Generated by Django 4.0.3 on 2022-04-02 16:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='member',
            field=models.ManyToManyField(blank=True, related_name='user_member_in_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
